# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Httpurr < Formula
  desc "HTTP status codes on speed dial"
  homepage "https://github.com/rednafi/httpurr"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/rednafi/httpurr/releases/download/v0.1.0/httpurr_Darwin_arm64.tar.gz"
      sha256 "557c31ca3afdbef16465448ad8a2993d7b6a52675ffba90504ce731c4717eaa8"

      def install
        bin.install "httpurr"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rednafi/httpurr/releases/download/v0.1.0/httpurr_Darwin_x86_64.tar.gz"
      sha256 "c93fb02cfd97d27e9ebaad370d514894abbaa361a38130139f60f994b59d8567"

      def install
        bin.install "httpurr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/rednafi/httpurr/releases/download/v0.1.0/httpurr_Linux_x86_64.tar.gz"
      sha256 "0d6b9d10fbb7786e0cba4971d483829f5fd10ad140b1f3a79420e0e5e1ecddda"

      def install
        bin.install "httpurr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rednafi/httpurr/releases/download/v0.1.0/httpurr_Linux_arm64.tar.gz"
      sha256 "f2d5cdc124d2d43d7d3b5b6a59145dc40164ebf5ea1c919034d675ad4f06f071"

      def install
        bin.install "httpurr"
      end
    end
  end
end
